---
  - name: "deploy app"
    hosts: localhost
    tasks:
      - name: "k8 task"
        k8s:
          kubeconfig: "rbroconfig"
          namespace: "default"
          state: "present"
          src: "deployment.yml"
